### ISSUE TITLE
IndexError: list index out of range (frag/network/decorate.py:225)

### ISSUE THREAD

**Issue by alanbchristie** [xchem/fragutils#40]
While testing an experimental stack and querying the graph database I stumbled upon a number of `IndexError` exceptions in the `decorate.py` module. Full stack trace: -

```
Internal Server Error: /api/vector/194/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/fields.py", line 1905, in to_representation
    return method(value)
  File "/code/viewer/serializers.py", line 380, in get_vectors
    out_data["indices"] = get_vect_indices_for_mol(obj.sdf_info)
  File "/usr/local/lib/python3.7/dist-packages/frag/network/decorate.py", line 101, in get_vect_indices_for_mol
    tot_dict = del_link_coord(input_mol, get_indices=True, iso_labels=False)
  File "/usr/local/lib/python3.7/dist-packages/frag/network/decorate.py", line 161, in del_link_coord
    x, Chem.MolFromMolBlock(input_mol), get_indices, ring_iso[i]
  File "/usr/local/lib/python3.7/dist-packages/frag/network/decorate.py", line 238, in get_atom_coords
    ind_list = find_atom_pairs(smiles_input, get_indices, iso_smiles)
  File "/usr/local/lib/python3.7/dist-packages/frag/network/decorate.py", line 225, in find_atom_pairs
    isotope = int(iso_matches[i][:-2])
IndexError: list index out of range
```

**Comment by alanbchristie** [comment]
## Root cause

The 500 originates in the upstream fragalysis package (`frag.network.decorate`), not in the backend itself.

`VectorsSerializer.get_vectors` (`viewer/serializers.py:506`) calls `get_vect_indices_for_mol()`, which descends into `find_atom_pairs()` (`frag/network/decorate.py:209`):

```python
matches = re.findall(XE_PATT, smiles_input)
if iso_smiles:
    iso_matches = re.findall(XE_PATT, iso_smiles)
...
for i, match in enumerate(matches):
    index = int(match[:-2])
    if iso_matches:
        isotope = int(iso_matches[i][:-2])   # <-- IndexError
```

 `matches` and `iso_matches` are extracted from two different SMILES strings (`smiles_input` vs `iso_smiles`). The loop iterates over matches but indexes iso_matches[i]. When the isomeric SMILES produces fewer `[<n>Xe]` tokens than the plain SMILES, `iso_matches[i]` is out of range -> `IndexError: list index out of range`.

Note the serializer already carries a "temporary patch" wrapping get_3d_vects_for_mol in try/except IndexError, but the sibling get_vect_indices_for_mol call on the next line is unguarded -- that is the exact line in the traceback.
